// data.js

export const technicalSkillsList = [
    // Habilidades de Comunicación y Relaciones Públicas
"Oratoria",
"Redacción Técnica",
"Comunicación Intercultural",
"Moderación de Reuniones",
"Facilitación de Diálogos",
"Negociación Internacional",
"Relaciones Diplomáticas",
"Comunicación No Violenta",

// Habilidades de Innovación y Emprendimiento
"Modelo Canvas",
"Lean Startup",
"Pitching",
"Investigación de Mercado Cualitativa",
"Gestión de Proyectos Innovadores",
"Design Thinking",
"Prototipado Rápido",
"Validación de Ideas",
"Financiamiento Colectivo (Crowdfunding)",
"Propiedad Intelectual",
"Patentes y Marcas",

// Habilidades Financieras y Contables
"Análisis de Estados Financieros",
"Presupuesto Personal",
"Planificación Fiscal",
"Valoración de Empresas",
"Inversiones",
"Criptomonedas",
"Blockchain para Negocios",
"Contabilidad Gerencial",
"Control Interno",
"Forensic Accounting",

// Habilidades de Logística y Cadena de Suministro
"Gestión de Almacenes",
"Optimización de Rutas",
"Sistemas WMS (Warehouse Management System)",
"Trazabilidad de Productos",
"Gestión de Inventarios Just in Time",
"Cross-Docking",
"Logística Inversa",
"Supply Chain Analytics",
"Transporte Multimodal",
"Compliance en Comercio Internacional",

// Habilidades de Agricultura y Medio Ambiente
"Agricultura Sostenible",
"Permacultura",
"Huertos Urbanos",
"Agroecología",
"Gestión de Recursos Hídricos",
"Conservación de Suelos",
"Silvicultura",
"Producción Orgánica",
"Control Biológico de Plagas",
"Manejo de Residuos Orgánicos",

// Habilidades de Arte y Cultura
"Diseño de Escenografía",
"Escultura",
"Pintura Digital",
"Caligrafía",
"Fotografía Documental",
"Arte Conceptual",
"Restauración de Obras de Arte",
"Curaduría",
"Arte Performático",
"Producción Cultural",

// Habilidades de Ciencia y Laboratorio
"Microscopía",
"Biotecnología",
"Bioinformática",
"Laboratorio Clínico",
"Química Analítica",
"Desarrollo de Fármacos",
"Control de Calidad",
"Validación de Métodos Analíticos",
"Genética Molecular",
"Biotecnología Ambiental",

// Habilidades de Educación Especializada
"Educación STEM",
"Educación Emocional",
"Educación Bilingüe",
"Educación Inclusiva",
"Gamificación Educativa",
"Neuroeducación",
"Educación a Distancia",
"Capacitación en Competencias Digitales",
"Formación en Inteligencia Artificial",
"Educación Financiera",

// Habilidades de Atención al Cliente y Servicio
"Gestión de Quejas y Reclamaciones",
"Experiencia del Cliente (CX)",
"Customer Journey Mapping",
"Servicio Postventa",
"Gestión de Devoluciones",
"Atención Telefónica Avanzada",
"Chatbots y Automatización de Servicios",
"Upselling en Retail",
"Cross-Selling en Banca",
"Servicio VIP",

// Habilidades de Industria Textil y Moda
"Estampación Textil",
"Tejido a Mano",
"Crochet",
"Bordado",
"Patronaje Digital",
"Moda Sostenible",
"Producción de Accesorios",
"Customización de Prendas",
"Textiles Inteligentes",
"Diseño de Uniformes",

// Habilidades de Energía y Medio Ambiente
"Instalación de Aerogeneradores",
"Mantenimiento de Parques Solares",
"Certificación LEED",
"Gestión de Residuos Industriales",
"Consultoría Ambiental",
"Compensación de Carbono",
"Auditorías Energéticas",
"Energía Eólica",
"Energía Hidráulica",
"Gestión de Aguas Residuales",

// Habilidades de Salud Mental y Bienestar
"Psicoterapia Cognitivo-Conductual",
"Mindfulness Corporativo",
"Coaching Ejecutivo",
"Terapia Familiar",
"Inteligencia Emocional en el Trabajo",
"Prevención del Burnout",
"Resiliencia Organizacional",
"Bienestar en el Trabajo",
"Psicología Positiva",
"Autocuidado Profesional",

// Habilidades de Seguridad y Defensa
"Seguridad Privada",
"Defensa Personal",
"Primer Respondiente",
"Seguridad Informática",
"Ciberseguridad Industrial",
"Protección de Datos Personales",
"Seguridad Física",
"Análisis de Amenazas",
"Seguridad en Eventos",
"Protección Ejecutiva",

// Habilidades de Transporte y Movilidad
"Conducción Defensiva",
"Transporte de Mercancías Peligrosas",
"Logística de Última Milla",
"Movilidad Sostenible",
"Planificación Urbana",
"Transporte Público",
"Bicicletas Eléctricas",
"Vehículos Autónomos",
"Optimización de Flotas",
"Normativas de Transporte",

// Habilidades de Derecho y Compliance
"Derecho Laboral",
"Derecho Corporativo",
"Derecho Tributario",
"Compliance Legal",
"Contratos Internacionales",
"Propiedad Intelectual",
"Mediación y Arbitraje",
"Derecho Penal Empresarial",
"Derecho Ambiental",
"Normativas ISO",

// Habilidades de Artesanía y Manualidades
"Encuadernación",
"Vitrales",
"Macramé",
"Origami",
"Quilling",
"Cerámica Artística",
"Joyería Artesanal",
"Decoración de Interiores con Elementos Naturales",
"Reutilización Creativa",
"Artesanía Textil",

// Habilidades de Turismo y Hospitalidad
"Turismo Sostenible",
"Ecoturismo",
"Turismo Cultural",
"Guía Turístico",
"Organización de Viajes",
"Gestión de Alojamientos",
"Marketing Turístico",
"Idiomas para Turismo",
"Protocolo y Etiqueta",
"Experiencias Inmersivas",

// Habilidades de Deportes y Fitness
"Entrenamiento Funcional",
"CrossFit",
"Yoga Terapéutico",
"Nutrición Deportiva",
"Entrenamiento Personalizado",
"Preparación Física",
"Recuperación Activa",
"Entrenamiento Mental",
"Deportes Extremos",
"Fitness Grupal",
];



export const softSkillsList = [
    "Comunicación efectiva",
    "Trabajo en equipo",
    "Liderazgo",
    "Empatía",
    "Resolución de problemas",
    "Adaptabilidad",
    "Pensamiento crítico",
    "Creatividad",
    "Gestión del tiempo",
    "Toma de decisiones",
    "Negociación",
    "Colaboración",
    "Orientación al cliente",
    "Manejo de conflictos",
    "Pensamiento estratégico",
    "Flexibilidad",
    "Autoconciencia",
    "Autogestión",
    "Conciencia social",
    "Gestión de relaciones",
    "Motivación personal",
    "Escucha activa",
    "Asertividad",
    "Capacidad de análisis",
    "Resolución de conflictos",
    "Iniciativa",
    "Habilidades interpersonales",
    "Persuasión",
    "Networking",
    "Gestión del estrés",
    "Orientación a resultados",
    // Habilidades adicionales
    "Creatividad e innovación", 
    "Capacidad para trabajar bajo presión", 
    // Más habilidades
    "Habilidades de presentación", 
    "Ética laboral", 
    // Habilidades relacionadas con la gestión
    "Capacidad para delegar", 
    // Habilidades en la toma de decisiones
    'Habilidades organizativas', 
   // Habilidades en la resolución de problemas
   'Pensamiento analítico', 
   'Capacidad para aprender rápidamente', 
   'Habilidad para trabajar con diversidad', 
   'Habilidad para recibir críticas constructivas',
   // Habilidades en la mediación
   'Mediación efectiva', 
   // Habilidades en la gestión del tiempo
   'Planificación eficaz',
   // Habilidades en la adaptabilidad
   'Adaptación a nuevas tecnologías',
   // Habilidades en el servicio al cliente
   'Atención al detalle',
   // Habilidades en el trabajo colaborativo
   'Sinergia en equipos',
   // Habilidades en la gestión emocional
   'Inteligencia emocional',
   // Habilidades en el liderazgo
   'Inspirar y motivar a otros',
   // Habilidades en la comunicación
   'Comunicación no verbal',
   // Habilidades en el pensamiento crítico
   'Evaluar información críticamente',
   // Habilidades en la creatividad
   'Generar ideas innovadoras',
   // Habilidades en el trabajo remoto
   'Colaboración virtual',
];


export const provincesAndMunicipalities = {
    'Pinar del Río': ['Pinar del Río', 'Consolación del Sur', 'Guane', 'La Palma', 'Los Palacios', 'Mantua', 'Minas de Matahambre', 'San Juan y Martínez', 'San Luis', 'Sandino', 'Viñales'],
'Artemisa': ['Artemisa', 'Alquízar', 'Bauta', 'Caimito', 'Guanajay', 'Güira de Melena', 'Mariel', 'San Antonio de los Baños', 'Bahía Honda', 'San Cristóbal', 'Candelaria'],
'Mayabeque': ['Mayabeque', 'Batabanó', 'Bejucal', 'Güines', 'Jaruco', 'Madruga', 'Melena del Sur', 'Nueva Paz', 'Quivicán', 'San José de las Lajas', 'San Nicolás de Bari', 'Santa Cruz del Norte'],
'La Habana': ['Arroyo Naranjo', 'Boyeros', 'Centro Habana', 'Cerro', 'Cotorro', 'Diez de Octubre', 'Guanabacoa', 'Habana del Este', 'Habana Vieja', 'La Lisa', 'Marianao', 'Playa', 'Plaza', 'Regla', 'San Miguel del Padrón'],
'Matanzas': ['Matanzas', 'Calimete', 'Cárdenas', 'Ciénaga de Zapata', 'Colón', 'Jagüey Grande', 'Jovellanos', 'Limonar', 'Los Arabos', 'Martí', 'Pedro Betancourt', 'Perico', 'Unión de Reyes'],
'Cienfuegos': ['Cienfuegos','Abreus','Aguada de Pasajeros','Cruces','Cumanayagua','Palmira','Rodas','Santa Isabel de las Lajas'],
'Villa Clara': ['Villa Clara','Caibarién','Camajuaní','Cifuentes','Corralillo','Encrucijada','Manicaragua','Placetas','Quemado de Güines','Ranchuelo','Remedios','Sagua la Grande','Santa Clara','Santo Domingo'],
'Sancti Spíritus': ['Sancti Spíritus','Cabaigúan','Fomento','Jatibonico','La Sierpe','Taguasco','Trinidad','Yaguajay'],
'Ciego de Ávila': ['Ciego de Ávila','Ciro Redondo','Baraguá','Bolivia','Chambas','Florencia','Majagua','Morón','Primero de Enero','Venezuela'],
'Camagüey': ['Camagüey','Carlos Manuel de Céspedes','Esmeralda','Florida','Guaimaro','Jimagüayú','Minas','Najasa','Nuevitas','Santa Cruz del Sur','Sibanicú','Sierra de Cubitas','Vertientes'],
'Las Tunas': ['Las Tunas','Amancio Rodríguez','Colombia','Jesús Menéndez','Jobabo'],
'Holguín': ['Holguín','Antilla','Báguanos','Banes','Cacocum','Calixto García','Cueto','Frank País','Gibara'],
'Santiago de Cuba': ['Santiago de Cuba ','Contramaestre ','Guamá ','Julio Antonio Mella ','Palma Soriano ','San Luis ','Segundo Frente ','Songo la Maya ','Tercer Frente'],
'Guantánamo': ['Guantánamo ','Baracoa ','Caimanera ','El Salvador ','Imías ','Maisí ','Manuel Tames ','Niceto Pérez ','San Antonio del Sur ','Yateras'],
'Isla de la Juventud': ['Isla de la Juventud'],
'Granma': ['Granma ',  'Bartolomé Masó ',  'Bayamo ',  'Buey Arriba ',  'Campechuela ',  'Cauto Cristo ',  'Guisa ',  'Jiguaní ',  'Manzanillo ',  'Media Luna ',  'Niquero ',  'Pilón ',  'Río Cauto ',  'Yara']
    // Agrega más provincias y municipios aquí
};

export const languagesList = [
    'Español',
    'Inglés',
    'Francés',
    'Alemán',
    'Italiano',
    'Portugués',
    'Chino (Mandarín)',
    'Japonés',
    'Ruso',
    'Árabe',
    'Hindi',
    'Bengalí',
    'Urdu',
    'Turco',
    'Vietnamita',
    'Coreano',
    'Tailandés',
    'Persa (Farsi)',
    'Malayo',
    'Sueco',
    'Danés',
    'Noruego',
    'Finlandés',
    'Checo',
    'Húngaro',
    'Griego',
    'Hebreo',
    'Indonesio',
    'Filipino (Tagalo)',
    'Swahili',
    'Serbio',
    'Croata',
    'Eslovaco',
    'Búlgaro',
    'Rumano',
    'Ucraniano',
    'Letón',
    'Lituano',
    'Estonio',
    'Macedonio',
    'Albanés',
    // Idiomas adicionales
    'Afrikáans',
    'Aimara',
    'Akan',
    'Albanés',
    'Amárico',
    'Armenio',
    'Asamés',
    'Azerbaiyano',
    'Bambara',
    'Baskir',
    'Belaruso',
    'Bhojpuri',
    'Birmano',
    'Bislama',
    'Bosnio',
    'Breton',
    'Catalán',
    'Cebuano',
    'Chamorro',
    'Checheno',
    'Chichewa',
    'Corsican',
    'Criollo Haitiano',
    'Dzongkha',
    'Esperanto',
    'Euskera',
    'Feroés',
    'Fiyiano',
    'Gaélico Escocés',
    'Gaélico Irlandés',
    'Gallego',
    'Georgiano',
    'Guaraní',
    'Guyaratí',
    'Haitiano',
    'Hausa',
    'Hawaiano',
    'Herero',
    'Hmong',
    'Igbo',
    'Ilocano',
    'Indígena (General)',
    'Interlingua',
    'Inuktitut',
    'Islandés',
    'Jemer',
    'Kannada',
    'Kazajo',
    'Khmer',
    'Kirguís',
    'Kinyarwanda',
    'Konkani',
    'Kurdo',
    'Lao',
    'Latín',
    'Luxemburgués',
    'Malgache',
    'Maldivo',
    'Maltese',
    'Maorí',
    'Marathi',
    'Mongol',
    'Nepalí',
    'Ojibwa',
    'Oromo',
    'Panyabí',
    'Pastún',
    'Polaco',
    'Quechua',
    'Quenya',
    'Romaní',
    'Rundi',
    'Samoano',
    'Sánscrito',
    'Sardo',
    'Sesotho',
    'Setswana',
    'Shona',
    'Sindhi',
    'Somalí',
    'Sundanés',
    'Sánscrito',
    'Tamil',
    'Tayiko',
    'Telugu',
    'Tibetano',
    'Tigrinya',
    'Tonga',
    'Tsonga',
    'Tulu',
    'Turcomano',
    'Uigur',
    'Valón',
    'Vasco',
    'Wolof',
    'Xhosa',
    'Yiddish',
    'Yoruba',
    'Zulú'
];