export const allJobs = [
  {
    id: 1,
    title: "Diseñador Web",
    company: "XYZ",
    location: "Madrid",
    description: "Buscamos un diseñador creativo con experiencia en UX/UI. El candidato ideal debe tener un fuerte portafolio que demuestre su capacidad para crear interfaces de usuario atractivas y funcionales. Además, se espera que tenga habilidades en investigación de usuarios y pruebas de usabilidad. El trabajo implica colaborar con desarrolladores y otros diseñadores para crear experiencias de usuario excepcionales. Se valorará la experiencia en diseño responsivo y la capacidad de trabajar bajo presión. El candidato debe estar familiarizado con herramientas como Figma, Sketch y Adobe Creative Suite. También se espera que tenga conocimientos en HTML y CSS para poder comunicarse efectivamente con el equipo de desarrollo. La creatividad, la atención al detalle y la habilidad para resolver problemas son esenciales para este puesto. Buscamos a alguien que esté dispuesto a aprender y crecer dentro de la empresa, contribuyendo a un ambiente de trabajo dinámico y colaborativo.",
    date: "01/01/2025",
    requirements: "Experiencia en diseño gráfico y herramientas como Figma.",
    benefits: "Seguro médico, flexibilidad horaria.",
    salary: "35,000 EUR anuales",
    applicationProcess: "Envía tu CV a careers@xyz.com antes del 15/01/2025.",
    culture: "Ambiente colaborativo y creativo.",
    category: "full-time",
    experienceLevel: "mid",
    type: "Estatal"
}

,
  {
      id: 2,
      title: "Desarrollador Frontend",
      company: "ABC",
      location: "Barcelona",
      description: "Se requiere experiencia en JavaScript y React.",
      date: "02/01/2025",
      requirements: "Conocimientos en HTML, CSS y frameworks modernos.",
      benefits: "Oportunidades de formación continua.",
      salary: "40,000 EUR anuales",
      applicationProcess: "Postula en nuestra web.",
      culture: "Cultura de innovación y aprendizaje da dasda kjahdkah kah kash kash kajshd kas hakj hdsakjdhask jha kdha kdahs kdah kdjash dka hjk.",
      category: "full-time",
      experienceLevel: "junior",
      type: "No estatal"
  },
  {
      id: 3,
      title: "Gerente de Marketing",
      company: "DEF",
      location: "Valencia",
      description: "Liderar el equipo de marketing.",
      date: "03/01/2025",
      requirements: "Experiencia previa en gestión de equipos.",
      benefits: "Bonos por rendimiento, seguro dental.",
      salary: "50,000 EUR anuales",
      applicationProcess: "Enviar CV a marketing@def.com.",
      culture: "Enfoque en resultados y trabajo en equipo.",
      category: "full-time",
      experienceLevel: "senior",
      type: "Estatal"
  },
  {
    id: 4,
    title: "Analista de Datos",
    company: "GHI",
    location: "Sevilla",
    description: "Analizar datos para mejorar las estrategias comerciales.",
    date: "04/01/2025",
    requirements: "Conocimientos en SQL y herramientas de análisis.",
    benefits: "Trabajo remoto disponible, formación pagada.",
    salary: "38,000 EUR anuales",
    applicationProcess: "Enviar tu CV a hr@ghi.com.",
    culture: "Ambiente inclusivo y diverso.",
    category: "part-time",
    experienceLevel: "mid",
    type:"Estatal"
  },
  {
    id: 5,
    title:"Desarrollador Backend", 
    company:"JKL", 
    location:"Bilbao", 
    description:"Experiencia en Node.js y bases de datos.", 
    date:"05/01/2025", 
    requirements:"Experiencia con APIs RESTful.", 
    benefits:"Días libres adicionales, participación en conferencias.", 
    salary:"45,000 EUR anuales", 
    applicationProcess:"Aplica a través de nuestro portal web.", 
    culture:"Fomentamos la creatividad y la autonomía.", 
    category:"full-time", 
    experienceLevel:"mid", 
    type:"No estatal"
  },
  {
    id: 6,
    title:"Desarrollador Full Stack", 
    company:"MNO", 
    location:"Madrid", 
    description:"Buscamos un desarrollador full stack con experiencia en MERN.", 
    date:"06/01/2025", 
    requirements:"Experiencia en MongoDB, Express, React y Node.js.", 
    benefits:"Plan de salud completo.", 
    salary:"55,000 EUR anuales", 
    applicationProcess:"Enviar CV a jobs@mno.com.", 
    culture:"Ambiente dinámico y colaborativo.", 
    category:"full-time", 
    experienceLevel:"senior", 
    type:"No estatal"
  },
  {
    id: 7,
    title:"Diseñador UX/UI", 
    company:"PQR", 
    location:"Barcelona", 
    description:"Diseño de interfaces intuitivas para aplicaciones web.", 
    date:"07/01/2025", 
    requirements:"Experiencia con herramientas como Sketch o Adobe XD.", 
    benefits:"Horarios flexibles y trabajo remoto.", 
    salary:"42,000 EUR anuales", 
    applicationProcess:"Postula enviando tu portafolio a hr@pqr.com.", 
    culture:"Cultura centrada en el usuario.", 
    category:"full-time", 
    experienceLevel:"mid", 
    type:"No estatal"
  },
  {
     id: 8,
     title:"Ingeniero DevOps",  
     company:"STU",  
     location:"Valencia",  
     description:"Implementar soluciones CI/CD para nuestros servicios.",  
     date:"08/01/2025",  
     requirements:"Conocimientos en Docker y Kubernetes.",  
     benefits:"Bono anual por desempeño.",  
     salary:"60,000 EUR anuales",  
     applicationProcess:"Aplicar a través de nuestro sitio web.",  
     culture:"Fomentamos la innovación tecnológica.",  
     category:"full-time",  
     experienceLevel:'senior',  
     type:'No estatal'
 },
 {
     id: 9,
     title:'Especialista SEO',  
     company:'YZA',  
     location:'Bilbao',  
     description:'Optimizar el contenido para mejorar el ranking SEO.',  
     date:'10/01/2025',  
     requirements:'Conocimiento avanzado de Google Analytics.',  
     benefits:'Capacitación continua y conferencias pagadas.',  
     salary:'36,000 EUR anuales',  
     applicationProcess:'Enviar CV a seo@yza.com.',  
     culture:'Ambiente creativo e innovador.',  
     category:'part-time',   
     experienceLevel:'junior',   
     type:'Estatal'
 },
 {
   id : 10,
   title:'Desarrollador Mobile',   
   company:'BCD',   
   location:'Madrid',   
   description:'Crear aplicaciones móviles para iOS y Android.',   
   date:'11/01/2025',   
   requirements:'Experiencia con React Native o Flutter.',   
   benefits:'Días libres adicionales y trabajo remoto opcional.',   
   salary:'50,000 EUR anuales',   
   applicationProcess:'Aplicar enviando tu CV a jobs@bcd.com.',   
   culture:'Fomentamos el trabajo en equipo.',   
   category:'freelance',   
   experienceLevel:'mid',
   type:'No estatal'
 },
 {
   id : 11,
   title:'Analista Financiero',   
   company:'EFG',   
   location:'Madrid',   
   description:'Realizar análisis financieros para la toma de decisiones estratégicas.',   
   date:'12/01/2025',   
   requirements:'Experiencia en análisis financiero y manejo avanzado de Excel.',   
   benefits:'Oportunidades de crecimiento profesional.',   
   salary:'48,000 EUR anuales',   
   applicationProcess:'Enviar CV a finance@efg.com.',   
   culture:'Enfoque en resultados y mejora continua.',   
   category:'full-time',   
   experienceLevel:'mid',
   type:'Estatal'
 },
 {
   id : 12,
   title:'Administrador de Sistemas',   
   company:'HIJ',   
   location:'Barcelona',   
   description:'Gestionar y mantener los sistemas informáticos de la empresa.',   
   date:'13/01/2025',   
   requirements:'Conocimientos en administración de servidores Linux.',   
   benefits:'Teletrabajo parcial disponible.',   
   salary:'52,000 EUR anuales',   
   applicationProcess:'Aplicar enviando tu CV a systems@hij.com.',   
   culture:'Ambiente técnico desafiante.',   
   category:'full-time',   
   experienceLevel:'mid',
   type:'No estatal'
 },
 {
   id : 13,
   title:'Desarrollador QA',   
   company:'KLM',   
   location:'Valencia',   
   description:'Realizar pruebas de calidad sobre las aplicaciones desarrolladas.',   
   date:'14/01/2025',   
   requirements:'Experiencia con herramientas de automatización de pruebas.',   
   benefits:'Formación continua y desarrollo profesional.',   
   salary:'38,000 EUR anuales',
   applicationProcess :'Enviar CV a qa@klm.com.',
   culture :'Cultura enfocada en la calidad.',
   category :'part-time',
   experienceLevel :'junior',
   type :'Estatal'
 },
 {
id : 14,
title : 'Coordinador de Proyectos',
company : 'WXY',
location : 'Barcelona',
description : 'Coordinar proyectos tecnológicos desde su inicio hasta su finalización.',
date : '18/01/2025',
requirements : 'Experiencia previa en gestión de proyectos.',
benefits : 'Capacitación continua.',
salary : '60,000 EUR anuales',
applicationProcess : 'Enviar CV a projects@wxy.com.',
culture : 'Enfoque en la mejora continua.',
category : 'full-time',
experienceLevel : 'senior',
type : 'No estatal'
},
{
id : 15,
title : 'Técnico Soporte IT',
company : 'ZAB',
location : 'Valencia',
description : 'Proveer soporte técnico a usuarios internos.',
date : '19/01/2025',
requirements : 'Conocimiento básico de redes y hardware.',
benefits : 'Oportunidades de crecimiento profesional.',
salary : '30,000 EUR anuales',
applicationProcess : 'Enviar CV a support@zab.com.',
culture : 'Ambiente dinámico y colaborativo.',
category : 'part-time',
experienceLevel : 'junior',
type : 'No estatal'
},
{
id : 16,
title : 'Desarrollador C#',
company : 'FGH',
location : 'Bilbao',
description : 'Desarrollar aplicaciones utilizando C# y .NET Framework.',
date : '20/01/2025',
requirements : 'Amplia experiencia como arquitecto software.',
benefits : 'Flexibilidad horaria y opción de teletrabajo.',
salary : '70,000 EUR anuales',
applicationProcess : 'Enviar CV a architect@fgh.com.',
culture : 'Innovación constante.',
category :'full-time',
experienceLevel :'senior'
},
{
id : 17,
title :"Desarrollador Python",
company :"RST",
location :"Madrid",
description :"Desarrollo de aplicaciones backend utilizando Python.",
date :"21/01/2025",
requirements :"Experiencia con Django o Flask.",
benefits :"Formación pagada.",
salary :"55,000 EUR anuales",
applicationProcess :"Enviar CV a jobs@rst.com.",
culture :"Cultura ágil.",
category :"full-time",
experienceLevel :"mid",
type :"No estatal"
},
{
id : 18,
title :"Gerente de Ventas",
company :"UVW",
location :"Barcelona",
description :"Liderar el equipo de ventas.",
date :"22/01/2025",
requirements :"Experiencia previa en ventas.",
benefits :"Comisiones atractivas.",
salary :"65,000 EUR anuales",
applicationProcess :"Enviar CV a sales@uvw.com.",
culture :"Ambiente competitivo.",
category :"full-time",
experienceLevel :"senior",
type :"Estatal"
},
{
id : 19,
title :"Consultor IT",
company :"XYZ Consulting",
location :"Sevilla",
description :"Brindar consultoría técnica a clientes.",
date :"23/01/2025",
requirements :"Conocimientos sólidos en infraestructura IT.",
benefits :"Trabajo remoto disponible.",
salary :"60,000 EUR anuales",
applicationProcess :"Enviar CV a hr@xyzconsulting.com.",
culture :"Enfoque centrado en el cliente.",
category :"freelance",
experienceLevel :"mid",
type :"No estatal"
},
{
id : 20,
title :"Arquitecto Software",
company :"ABC Tech",
location :"Bilbao",
description :"Diseñar soluciones arquitectónicas para proyectos complejos.",
date :"24/01/2025",
requirements :"Amplia experiencia en arquitectura software.",
benefits :"Bono por desempeño anual.",
salary :"75,000 EUR anuales",
applicationProcess :"Enviar CV a careers@abctech.com.",
culture :"Innovación constante.",
category :"full-time",
experienceLevel :"senior",
type :"Estatal"
}
];
